version: "2.6"

services:
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    ports:
      - 27017:27017
  item-app:
    image: jovizulfikar/item-app:v1
    command: sh -c "npm install --production --unsafe-perm && npm run build && npm run start"
    ports:
      - 80:8080
    volumes: 
      - ./:/app
    links:
      - "item-db:item-db"
    environment:
      NODE_ENV: production
      DB_HOST: item-db
volumes:
  app-db:
  